### ISSUE TITLE
volume create breaks on JS test cloud

### ISSUE THREAD

**Issue by beckbw** [eriksf/atmosphere-cli#2]
volume create on TACC cloud on jetstream:

`atmo volume create --identity  08653592-af99-4f47-8c6d-3709a6deaf02  --size 10 --project  a9d28bb7-44d6-4914-8d1a-64673d12ebf2  --description "beckbw Volume on TACC" "beckbw-Volume-TACC"`

+-------------+--------------------------------------+
| Field       | Value                                |
+-------------+--------------------------------------+
| id          | 2949                                 |
| uuid        | 60fb6926-7950-477f-b252-f2e45a4467ab |
| name        | beckbw-Volume-TACC                   |
| description | beckbw Volume on TACC                |
| size        | 10                                   |
| project     | testing                              |
| provider    | Jetstream - TACC                     |
| user        | beckbw                               |
| start_date  | 2018-08-30T21:12:53.384321Z          |
+-------------+--------------------------------------+
`

volume create on jetstream test cloud:

`atmo volume create --identity  b6bf0d64-1ed2-461d-bffa-10d73f9d905c  --size 10 --project  7672413a-0bcf-4629-8b09-37f227237d46  --description "beckbw Volume on Jetstream_Test_Cloud" "beckbw-Volume-Jetstream_Test_Cloud"`

`ERROR: string indices must be integers, not str`
`Error, volume not created! Make sure to supply a name, identity, size, project, and description.`

**Comment by eriksf** [comment]
This was not a CLI issue. Fixed in newest Atmosphere release.
